name: Run CLI Command on Pull Request

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        description: 'Deployment environment'
        required: true
        default: 'NOT_DEFINED'

permissions:
  id-token: write
  contents: read

jobs:
  run-cli-command:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Azure Login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Print env_name
        run: |
          echo "Deployment environment is: ${{ inputs.env_name }}"

      - name: 'Run Azure commands'
        run: |
          az account show
          az group list
          