# name: Run CLI Command on Pull Request

# on:
#   pull_request:
#     types: [opened, synchronize]

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   run-cli-command:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: 'Azure Login'
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZURE_CLIENT_ID }}
#           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

#       - name: 'Run Azure commands'
#         run: |
#           az account show
#           az group list test

name: Run CLI Command on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  call-stage-template:
    uses: ./.github/workflows/helloStaging.yml
    with:
      env_name: 'Development'